### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by CWBudde**
I've been using your script as part of my "how to cheat in a computer game" lesson with my kids. After a simple example they wanted to hack one of their favorite games. Unfortunately, it wasn't as easy as the first examples, but thanks to this script we've been able to make it.

By reviewing the script we found (and fixed) a couple of minor issues.

### CODE REVIEW

**Comment by GoobyCorp** [comment]
No problem, did this actually work for you? I was under the impression that it didn't work anymore.

**Comment by CWBudde** [comment]
Yes, it worked for me. There were a few glitches and eventually I'm marked as cheater now, but since I am through with the game anyway, it's not that critical. It's just the kids who still want to play it, but I hope that after being able to cheat it arbitrary, they will soon loose interest in it (at least it worked for me in the past).

**Comment by CWBudde** [comment]
Oh, I forgot to mention: We didn't yet used it to the max. Just a few more gems, a few more pearls were satisfying for now.

**Comment by GoobyCorp** [comment]
Did you make sure the costumes were in order? They're required to be in the order they were decompiled in.

**Pull request closed without merging**
